# Generated by Django 2.1.7 on 2019-05-18 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Catergory',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='despensoryStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Despensory Storage',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='medicineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('category_type_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash_rmc.Category')),
            ],
            options={
                'verbose_name_plural': 'Medicine Category',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='medicineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_details', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Items',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='medicineStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('medicine_item_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash_rmc.medicineItems')),
            ],
            options={
                'verbose_name_plural': 'Medicine Storage',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='medicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_type_name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Type',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='medicineitems',
            name='medicine_type_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dash_rmc.medicineType'),
        ),
    ]
